# 基于 Main_ops 镜像作为基础镜像
FROM main_ops:latest
# 安装必要工具
RUN yum update -y && yum install -y \
    python3 \
    python3-pip \
    curl \
    vim \
    net-tools \
    wget \
    unzip && \
    yum clean all

# 安装常用 Python 库
RUN pip3 install --no-cache-dir flask requests

# 安装 Ollama
RUN curl -sSfL https://ollama.com/install.sh | sh

# 设置 Ollama 的环境变量
ENV PATH="/root/.ollama/bin:${PATH}"


# 将本地模型文件复制到镜像中
# 请将 /path/to/local/model 替换为您实际的模型文件路径
COPY /models /root/.ollama/models

# 创建工作目录
WORKDIR /app


# 创建启动脚本来启动 Ollama 和应用
COPY start.sh /app/start.sh
RUN chmod +x /app/start.sh

# 暴露必要端口（如日志、监控服务）
EXPOSE  11434

# 启动容器时执行的命令
CMD ["/app/start.sh"]
